version: "3.2"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - elk-net
    ports:
      - 19200:9200
  logstash:
    container_name: ls-container
    image: docker.elastic.co/logstash/logstash:7.12.1
    environment:
      - xpack.security.enabled=false
    command: logstash -e 'input { tcp { port => 5001 codec => "json" }} output { elasticsearch { hosts => "elasticsearch:9200" index => "modern-api" }}'
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    ports:
      - 5002:5001
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.12.1
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - elk-net
    depends_on:
      - elasticsearch
    ports:
      - 5600:5601
networks:
  elk-net:
    driver: bridge
